// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5qyvzCgg_EZvzM8K9Hu-6dS8HnnLgoTY',
    appId: '1:876515520923:web:27dcc7a776c7551a26713e',
    messagingSenderId: '876515520923',
    projectId: 'shitzu-58831',
    authDomain: 'shitzu-58831.firebaseapp.com',
    storageBucket: 'shitzu-58831.firebasestorage.app',
    measurementId: 'G-QXJ3JZF06Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3Oautm2Rq_rO8mGK7ipVYQ4S5WvzpNkQ',
    appId: '1:876515520923:android:66712ffd0b3d5ed926713e',
    messagingSenderId: '876515520923',
    projectId: 'shitzu-58831',
    storageBucket: 'shitzu-58831.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-J00mF61G99JHCyb87R_fVVi99s3kBvU',
    appId: '1:876515520923:ios:dec3cc63a79e637a26713e',
    messagingSenderId: '876515520923',
    projectId: 'shitzu-58831',
    storageBucket: 'shitzu-58831.firebasestorage.app',
    iosBundleId: 'com.example.shitzu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-J00mF61G99JHCyb87R_fVVi99s3kBvU',
    appId: '1:876515520923:ios:dec3cc63a79e637a26713e',
    messagingSenderId: '876515520923',
    projectId: 'shitzu-58831',
    storageBucket: 'shitzu-58831.firebasestorage.app',
    iosBundleId: 'com.example.shitzu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5qyvzCgg_EZvzM8K9Hu-6dS8HnnLgoTY',
    appId: '1:876515520923:web:c79ad1b7f22a689626713e',
    messagingSenderId: '876515520923',
    projectId: 'shitzu-58831',
    authDomain: 'shitzu-58831.firebaseapp.com',
    storageBucket: 'shitzu-58831.firebasestorage.app',
    measurementId: 'G-0DJG9TF8F5',
  );
}
